### ISSUE TITLE
Laravel  - VUEJS

### ISSUE THREAD

**Issue by majweb** [nonsalant/contract#19]
Please rewrite to laravel plus vuejs (inertiajs)

**Comment by nonsalant** [comment]
I don’t think putting the Laravel framework in a single file would be a good idea.

**Comment by majweb** [comment]
Maybe only vuejs

**Comment by majweb** [comment]
Make video on yotube how made maybe

**Comment by nonsalant** [comment]
There are definitely no plans to do anything with Laravel and/or Vue on this project, this includes educational content which I would not be in the best position to make even I had the time for it (which I don’t). 

Also, please consider not going into Open Source projects’ Issues and demanding a complete re-write in your preferred language/framework. I honestly thought that was a joke at first :)
