### ISSUE TITLE
Emails not sending after both parties sign

### ISSUE THREAD

**Issue by DavidAllmon** [nonsalant/contract#22]
Not sure how to configure this, but I am not receiving emails after the contract is signed.

**Comment by nonsalant** [comment]
Not sure if you’ve tested this already, but I’ve isolated just the code responsible for sending the email(s) (also added a simplified getHtmlUrl() function at the top so it doesn’t depend on other stuff). 

The code below is from: https://github.com/nonsalant/contract/blob/main/generator/data/more-data/php-partials/contract_footer.phpsrc with the `sendEmails("email@example.com", "email2@example.com")` function call added at the end — you can edit that line and put the code on your server to test the email functionality. 

This should help you rule out any problems with the server not sending the emails or your email provider not showing them (eg putting the emails in spam). 

```php
<?php

function getHtmlUrl() {
  return 'https://example.com';
}

// Function to email notifications; gets called when Client signs
function sendEmails($clientEmail, $devEmail)
{
  if ($clientEmail) {
    $headers = "From: " . $devEmail . "\r\nMIME-Version: 1.0\r\nContent-Type: text/html; charset=ISO-8859-1\r\n";
    $msg = 'The contract was signed. You can <a href="' . getHtmlUrl() . '">view or download this contract from here</a>.';
    mail($clientEmail, 'Contract signed', $msg, $headers);
  }
  if ($devEmail) {
    $headers = "From: " . $clientEmail . "\r\nMIME-Version: 1.0\r\nContent-Type: text/html; charset=ISO-8859-1\r\n";
    $msg = '<p>A new contract was signed. You can <a href="' . getHtmlUrl() . '">view or download this contract from here</a>.</p>';
    $msg .= 'The contract was signed by: ' . $clientEmail;
    mail($devEmail, 'Contract signed!', $msg, $headers);
  }
}

// testing email
sendEmails("email@example.com", "email2@example.com");

?>
